version: 2.1

jobs:
  build_test_publish:
    machine: true
    steps:
      - restore_cache:
          keys:
            - sbt-cache-{{ .Branch }}-{{ checksum "project/plugins.sbt" }}-{{ checksum "build.sbt" }}-{{ .Environment.CIRCLE_SHA1 }}
            - sbt-cache-{{ .Branch }}-{{ checksum "project/plugins.sbt" }}-{{ checksum "build.sbt" }}
            - sbt-cache-{{ .Branch }}-{{ checksum "project/plugins.sbt" }}
            - sbt-cache-{{ .Branch }}
            - sbt-cache
      - run:
          name: Scala Native Environment
          command: |
            curl https://raw.githubusercontent.com/scala-native/scala-native/v0.4.0-M2/scripts/travis_setup.sh | bash -
      - run:
          name: Run Tests
          command: sbt test
      - save_cache:
          key: sbt-cache-{{ .Branch }}-{{ checksum "project/plugins.sbt" }}-{{ checksum "build.sbt" }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - "~/.cache/coursier/v1"

workflows:
  version: 2
  build_test_publish:
    jobs:
      - build_test_publish
